baseURL = 'https://www.cesf.ca/'
defaultContentLanguage = 'pt'
defaultContentLanguageInSubdir = true
theme = 'congo'

enableRobotsTXT = true
summaryLength = 30

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
