colorScheme = "slate"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
disableImageOptimization = false
highlightCurrentMenuArea = true

fingerprintAlgorithm = "sha256"

defaultBackgroundImage = "img/banner.png"

[header]
  layout = "fixed"

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background"
  homepageImage = "img/banner.png"
  showRecent = false
  layoutBackgroundBlur = true

[article]
  showDate = false
  showDateUpdated = false
  showAuthor = false
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = false

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = false
  showTaxonomies = false
  groupByYear = false

[taxonomy]
  showTermCount = true
