baseURL = 'https://cesf.ca/'
languageCode = 'pt-br'
title = 'CESF - Centro Espírita São Francisco'
defaultContentLanguage = 'pt'
theme = 'ananke'

[params]
social = [
  { name = "Facebook", url = "https://www.facebook.com/cesf" },
  { name = "YouTube", url = "https://www.youtube.com/cesf" },
  { name = "Instagram", url = "https://www.instagram.com/cesf" }
]

[languages.pt]
title = "CESF - Centre d'Études Spirites Fraternité"
languageCode = "pt-br"
weight = 1

[languages.fr]
title = "CESF - Centre d'Études Spirites Fraternité"
languageCode = "fr-ca"
weight = 2

[languages.en]
title = "CESF - Centre d'Études Spirites Fraternité"
languageCode = "en-ca"
weight = 3

ignoreLogs = ["warning-goldmark-raw-html"]
