backend:
  name: git-gateway
  branch: main

media_folder: static/images
public_folder: /images

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pt"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}